# Generated by Django 3.1.2 on 2020-12-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='Nombre')),
                ('nacionalidad', models.TextField(verbose_name='Nombre de la nacionalidad')),
                ('victorias', models.IntegerField(verbose_name='Número de victorias')),
                ('poles', models.IntegerField(verbose_name='Número de poles')),
                ('temporadas', models.IntegerField(verbose_name='Número de temporadas disputadas')),
                ('carreras', models.IntegerField(verbose_name='Número de carreras disputadas')),
                ('campeonatos', models.IntegerField(verbose_name='Número de campeonatos del mundo de constructores ganados')),
                ('puntos', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='Número de puntos obtenidos durante su carrera deportiva')),
            ],
        ),
    ]
