# Generated by Django 3.1.2 on 2021-01-17 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votante', models.TextField(verbose_name='Votante')),
                ('puntuacion', models.IntegerField(verbose_name='Puntos sobre 5 otorgados')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.piloto')),
            ],
        ),
    ]
