# Generated by Django 3.1.2 on 2020-12-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201228_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuderia',
            name='pilotos',
            field=models.ManyToManyField(to='main.Piloto'),
        ),
    ]
